openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    contact app project
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-7-jzi1.onrender.com
paths:
  /contacts/{contactId}:
    get: 
      $ref: ../swagger/path/{id}/get.yaml
    delete:
      $ref: ../swagger/path/{id}/delete.yaml
    patch:
      $ref: ../swagger/path/{id}/patch.yaml

  /contacts:
    post:
      $ref: ../swagger/path/post.yaml
    get:
      $ref: ../swagger/path/get.yaml
            

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer